name: exploitdb-papers
title: ExploitDB Papers
base: core22
adopt-info: exploitdb-papers

license: GPL-3.0-or-later
source-code: https://gitlab.com/exploit-database/exploitdb-papers.git
issues: https://github.com/JitPatro/exploitdb-papers/issues

summary: Exploit Database's Papers
description: |
  The Exploit Database is an archive of public exploits and corresponding vulnerable software,
  developed for use by penetration testers and vulnerability researchers. Its aim is to serve as the
  most comprehensive collection of exploits, shellcode and papers gathered through direct
  submissions, mailing lists, and other public sources, and present them in a freely-available and
  easy-to-navigate database. The Exploit Database is a repository for exploits and Proof-of-Concepts
  rather than advisories, making it a valuable resource for those who need actionable data right
  away.
  You can learn more about the project here:- https://www.exploit-db.com/ and
  here:- https://www.exploit-db.com/history (History).
  Installation: `sudo snap install exploitdb-papers`

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  exploitdb-papers:
    interface: content
    content: papers
    source:
      read:
        - $SNAP/opt/exploitdb-papers

parts:
  exploitdb-papers:
    plugin: nil
    source: https://gitlab.com/exploit-database/exploitdb-papers.git

    override-pull: |
      craftctl default
      craftctl set version=$(git describe)

    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/opt/exploitdb-papers
      cp -r ./* $CRAFT_PART_INSTALL/opt/exploitdb-papers/
      craftctl default
